name: Build and Release Quiz App

on:
  push:
    branches: [ main ]  # 태그 필요 없음! 메인에 코드만 올라오면 바로 빌드 시작

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests Pillow pyinstaller

      - name: Build with PyInstaller
        shell: bash
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            pyinstaller --noconsole --onefile \
            --icon="icon.ico" \
            --add-data "기본형_심볼-03.jpg;." \
            --add-data "icon.ico;." \
            --name "연세_의학용어_마스터" Voca.py
          else
            pyinstaller --windowed --onefile \
            --icon="icon.ico" \
            --add-data "기본형_심볼-03.jpg:." \
            --add-data "icon.ico:." \
            --name "연세_의학용어_마스터" Voca.py
            cd dist
            zip -r Voca_Mac.zip 연세_의학용어_마스터.app
          fi

      - name: Release App
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "latest-build"  # 항상 같은 이름으로 덮어씌움
          files: |
            dist/연세_의학용어_마스터.exe
            dist/Voca_Mac.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
