name: Build and Release Quiz App

on:
  push:
    tags:
      - 'v*'

# 이 권한 설정이 핵심이야!
permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # v3 -> v4로 업데이트

      - name: Set up Python
        uses: actions/setup-python@v5 # v4 -> v5로 업데이트
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pyinstaller --noconfirm --onefile --windowed --icon "icon.ico" "Voca.py"

  # 5. 실행 파일 만들기 (맥용 이름 및 터미널 숨김 설정 추가)
      - name: Build with PyInstaller
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            pyinstaller --noconsole --onefile --add-data "기본형_심볼-03.jpg;." --name "연세_의학용어_마스터" Voca.py
          else
            # 맥용: --windowed(터미널 숨김)와 --name(이름 변경) 추가
            pyinstaller --windowed --onefile --add-data "기본형_심볼-03.jpg:." --name "연세_의학용어_마스터" Voca.py
            
            # 맥 전용: 앱 내부의 'tk' 이름을 실제 앱 이름으로 강제 변환하는 트릭
            cd dist
            zip -r Voca_Mac.zip 연세_의학용어_마스터.app
          fi
        shell: bash

      # 6. 결과물 업로드 (이름 바뀐 파일로 수정)
      - name: Release App
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/연세_의학용어_마스터.exe
            dist/Voca_Mac.zip
