name: Build and Release Quiz App

on:
  push:
    tags:
      - 'v*'

# 이 권한 설정이 핵심이야!
permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # v3 -> v4로 업데이트

      - name: Set up Python
        uses: actions/setup-python@v5 # v4 -> v5로 업데이트
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller Pillow requests

      - name: Build with PyInstaller
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            pyinstaller --noconsole --onefile --add-data "기본형_심볼-03.jpg;." Voca.py
          else
            pyinstaller --windowed --onefile --add-data "기본형_심볼-03.jpg:." Voca.py
          fi
        shell: bash

      - name: Release App
        uses: softprops/action-gh-release@v2 # v1 -> v2로 업데이트
        with:
          files: |
            dist/Voca.exe
            dist/Voca.app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
